// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmrrtudujhgosevszklr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtcnJ0dWR1amhnb3NldnN6a2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTE1MTcsImV4cCI6MjA2OTE2NzUxN30.qHbP62uSCcfO-LB-nD7nUvIj3v_ayNUioFrttaXZxQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});